### ISSUE TITLE
Unable to load WebCrypto.js on iOS 9.3-9.3.3

### ISSUE THREAD

**Issue by ghost** [etienne-martin/WebCrypto.swift#2]
It works perfectly on iOS 10
![screen shot 2017-05-28 at 03 32 09](https://cloud.githubusercontent.com/assets/5307981/26524894/45a7d3c6-4356-11e7-8950-23b7a55fee45.png)

**Comment by premrajD** [comment]
@etienne-martin, I am also facing the same issue on iOS 9.x.  I did try to follow some posts to resolve the issue on my own. It did not help either.

**Comment by ghost** [comment]
I am now using RNCryptor. It works both on iOS 9 and 10.

**Comment by etienne-martin** [comment]
Problem solved!

Thanks for taking the time to report about the issue.

Today I learned that iOS 9 doesn't support the ES6 `const` keyword.

Here's the culprit: https://github.com/etienne-martin/WebCrypto.swift/commit/981058516662dc842097d31164dc5d54c2e27af2#diff-714c7be7ac90b304cdf80ff10539da66R363

Thanks again.
