### ISSUE TITLE
Get crypted String

### ISSUE THREAD

**Issue by mobilestar0223** [etienne-martin/WebCrypto.swift#5]
Hello
I can get hex string from crypted data, but I want to get crypted text.
How can I get crypted text from crypted data?
And how can I convert crypted text to crypted data for decrypt?
Thanks.

**Comment by etienne-martin** [comment]
Hi there, I've updated the [Data types conversion section](https://github.com/etienne-martin/WebCrypto.swift#data-types-conversion) of the README with information regarding your questions.

**How can I get crypted text from crypted data?** 

Convert your ```Data``` to a base64 string:

```swift
let base64 = data.base64EncodedString(options: [])
```

**How can I convert crypted text to crypted data for decrypt?**

Convert the base64 string to ```Data```:

```swift
let data = Data(base64Encoded: base64, options: .ignoreUnknownCharacters)
```

Hope this helps!
