### ISSUE TITLE
Cannot decrypt from AES encrypted code

### ISSUE THREAD

**Issue by enx1998** [etienne-martin/WebCrypto.swift#6]
Hi Etienne,
I cannot decrypt an AES encrypted string. Here follows the code I wrote:
```Swift
let code = "6yVJAXlqQGli1wJWlcQoFeQVD/BQR3TDQNJZe1/gQQ5tCN6pRe0gOlAkv1CWTA3ZjXdntMooxI7bm9rphV+DyqGyXRo34Ou38v+GqnSfY5N3m30GH3ieUa20RxdX9cUmtQCxJaDC47C79ybWkFRuXWHmqONVFxXVe4ZqyZBDy+a2zLxLufHEB9mJkH5DEID1d6bcRteONAb7KYbFkJLGbQ=="
          
let input = Data(code.utf8)
let plainPassword="pd$83j@Fs3s13bZP";
let plainIV="aNdh284629324F32";
        
let key = crypto.hexEncodedStringFromData(Data(plainPassword.utf8));
let iv = crypto.hexEncodedStringFromData(Data(plainIV.utf8));
           
self.crypto.decrypt(data: input, key: key, iv: iv, callback: {(decrypted: Data?, error: Error?) in
       print(String(data: decrypted!, encoding: .utf8)!)
})
```

This is the result that I have executing the above code: 

> ««Ð8ë;xv1t!Õ(öaDM×# ?Ú §oàÁ Ï×jë½ÂÙ'¶Ý¢£ÇKËOUTüv2\ -­@ë3å±gÁý_Ìc°ÃØFZ@@ö(}Ú HwXSj±>±èYÆ^ÑÑY^ Õ ëú&Lqí]r[ ú ¨3Æ î%õDÞ£g9|¿ãËÓ{G km'&  ÝÕÆïw/%[¯j& ;5Åw¡dK }·± 6³S&æ6§C ¶óþæþ0hä 
[÷ {¾çñPPîR>Á\5pjz Ø$ $Ø_0Ûýã ÙK ÕÔÓ½¸.Pþ÷tÀÊQ Þ ¯YÈ@ m VzÉÉ¶:î}Æ6&ÿàj¬

I wrote the same example in js (you can find the code at https://jsfiddle.net/jwz1dx4a/) and the result is ok:  
```
{"user_info":{"id":4037,"username":"pippo","company_name":"Pippo","license_number":"FK01455-3","password":"pippo123"},"code":"200","msg":"login ok"}
```
Can you help me out?  

Thanks, Vincenzo

**Comment by etienne-martin** [comment]
Hi Vincenzo,

I managed to get it working. You were almost there!

The problem was with the way you converted your encrypted string to `Data`.

Your encrypted string is base64-encoded, you need to decode it before converting it to `Data`.

Here's a helper function that does both the decoding and conversion to the `Data` format:

```swift
let input = Data(base64Encoded: base64String, options: .ignoreUnknownCharacters)!
```

And here's a working example:

```swift
let base64String = "6yVJAXlqQGli1wJWlcQoFeQVD/BQR3TDQNJZe1/gQQ5tCN6pRe0gOlAkv1CWTA3ZjXdntMooxI7bm9rphV+DyqGyXRo34Ou38v+GqnSfY5N3m30GH3ieUa20RxdX9cUmtQCxJaDC47C79ybWkFRuXWHmqONVFxXVe4ZqyZBDy+a2zLxLufHEB9mJkH5DEID1d6bcRteONAb7KYbFkJLGbQ=="
let input = Data(base64Encoded: base64String, options: .ignoreUnknownCharacters)!
        
let plainPassword = "pd$83j@Fs3s13bZP"
let plainIV = "aNdh284629324F32"
        
let key = crypto.hexEncodedStringFromData(Data(plainPassword.utf8))
let iv = crypto.hexEncodedStringFromData(Data(plainIV.utf8))
        
crypto.decrypt(data: input, key: key, iv: iv, callback: {(decrypted: Data?, error: Error?) in
    print(String(data: decrypted!, encoding: .utf8)!)
})
```

Thanks for the concise code samples,

Hope this helps!

**Comment by etienne-martin** [comment]
Also, take a look at the [Data types conversion section](https://github.com/etienne-martin/WebCrypto.swift#data-types-conversion) of the README for more information.

**Comment by enx1998** [comment]
Thanks for the quick reply,
I found the problem: I was using an old version of the library (WebCrypto.js) that had a problem and won't decrypt the code; after using the new version everything is working correctly. 

Thanks again for the help,
bye Vincenzo
