### ISSUE TITLE
Want to decrypt with password for 128 bit encryption?

### ISSUE THREAD

**Issue by KDLNiranjan** [etienne-martin/WebCrypto.swift#7]
You mentioned: WebCrypto.swift supports AES-128, AES-192, and AES-256. It will pick the variant by the size of the key you pass in. If you use a password, AES-256 will be used.

But the content which i want to decrypt is AES 128 ECB pkcs7 with password. How to decrypt with password for 128 bit  with your library?

**Comment by KDLNiranjan** [comment]
Anybody working with this issues. Please answer.

**Comment by KDLNiranjan** [comment]
Please answer, anybody working on this issue.

**Comment by etienne-martin** [comment]
As stated in [the documentation](https://github.com/etienne-martin/WebCrypto.swift#aes), if you use a password, AES-256 will be used.

You can try to fiddle around with the key derivation function at line 330 of [source.js](https://github.com/etienne-martin/WebCrypto.swift/blob/master/source.js#L330).
