### ISSUE TITLE
Convery crypto.js algorithm to Swift

### ISSUE THREAD

**Issue by anitaa1990** [etienne-martin/WebCrypto.swift#9]
Hi, I would like to know how to use the below js method to work in Swift:

let key = "Q8pTgdOC7h25qKVncJlzDA=="
let message = "TestAnitaa009"
let base64Key = CryptoJS.enc.Base64.parse(key);

var iv = base64Key

let encryptedValue = CryptoJS.AES.encrypt(message, base64Key, {
mode: CryptoJS.mode.CBC,
padding: CryptoJS.pad.Pkcs7,
iv: base64Key
});

//The above code outputs = Oz9b31UvNTW8rFfGUOfB5A==

I tried using this library to help to do the same in Swift. But I am not able to. Any help is appreciated. Thanks a lot

**Comment by anitaa1990** [comment]
Got it working! Thanks

**Comment by etienne-martin** [comment]
Awesome! Can you show people how you made it work?

Also, you can ommit the IV option when using password-based encryption, it’s unnecessary.

**Comment by anitaa1990** [comment]
Hey, sorry for the delayed reply. This is logic that worked for me in the end:
```swift
func encryptValue(_ base64Key: String, _ value: String) {
    let base64KeyData = Data(base64Encoded: base64Key)!
    let hexKey = base64KeyData.map { String(format: "%02x", $0) }.joined()
    let valuedata = Data(value.utf8)
    crypto.encrypt(data: valuedata, key: hexKey, iv: hexKey, callback: {(encrypted: Data?, error: Error?) in
        if let error = error {
            print(error)
        } else {
            print(encrypted!.base64EncodedString())
        }
    })
} 
```

Thanks for the awesome library

**Comment by etienne-martin** [comment]
Be careful, the value of the key should never be the same as the value of the IV. 

Also as a rule of thumb, never re-use an initialization vector. Always generate a new IV every time you encrypt.

**Comment by anitaa1990** [comment]
Point noted :). 
Actually the key is fetched from a back end api each time and it's a different one each time. And i get the point about not using the key as iv but the requirement I got was to reuse the key as iv.
